ci:
  collect:
    url: ['http://localhost:3000']
    startServerCommand: npm run start
    startServerReadyPattern: started server on
    numberOfRuns: 1
    settings:
      preset: desktop
    assertions:
      uses-rel-preload: 'off'
      uses-rel-preconnect: 'off'
  upload:
    target: temporary-public-storage
