packages:
  - './*'

catalogs:
  analysis:
    '@next/bundle-analyzer': ^15.4.0-canary.51
    '@vercel/speed-insights': ^1.2.0
    react-scan: ^0.3.4

  # 前端依赖 (Frontend development)
  frontend:
    '@docsearch/react': ^3.9.0
    '@ducanh2912/next-pwa': ^10.2.9
    '@hookform/resolvers': ^5.1.1
    '@next/bundle-analyzer': ^15.4.0-canary.51
    '@t3-oss/env-nextjs': ^0.13.8
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    cobe: ^0.6.4
    cva: 1.0.0-beta.3
    geist: ^1.4.2
    merge-refs: ^2.0.0
    motion: ^12.17.0
    next: ^15.2.4
    next-themes: ^0.4.6
    nuqs: ^2.4.3
    react: 19.0.0
    react-dom: 19.0.0
    react-email: 4.0.3
    react-hook-form: ^7.57.0
    react-intersection-observer: ^9.16.0
    react-medium-image-zoom: ^5.2.14
    react-spring: ^10.0.1
    react-textarea-autosize: ^8.5.9
    rss: ^1.2.2
    tinycolor2: ^1.6.0
    use-debounce: ^10.0.5
    zustand: ^5.0.5

  backend:
    '@octokit/rest': ^22.0.0
    '@tanstack/react-query': ^5.80.6
    '@trpc/client': 11.0.0-rc.666
    '@trpc/react-query': 11.0.0-rc.666
    '@trpc/server': 11.0.0-rc.666
    '@upstash/ratelimit': ^2.0.5
    '@upstash/redis': ^1.35.0
    better-auth: ^1.2.9
    better-call: ^1.0.9
    drizzle-orm: ^0.44.2
    js-sha512: ^0.9.0
    pg: ^8.16.0
    resend: ^4.5.2

  build:
    '@vitejs/plugin-react': ^4.5.2
    babel-plugin-react-compiler: 19.0.0-beta-714736e-20250131
    next: 15.3.3
    sharp: ^0.34.2
    typescript: 5.7.3

  mdx:
    '@content-collections/cli': ^0.1.6
    '@content-collections/core': ^0.9.0
    '@content-collections/mdx': ^0.2.2
    '@content-collections/next': ^0.2.6
    '@shikijs/rehype': ^3.6.0
    '@shikijs/transformers': ^3.6.0
    markdown-to-jsx: ^7.7.6
    github-slugger: ^2.0.0
    remark: ^15.0.1
    remark-gfm: ^4.0.1
    shiki: ^3.6.0
    unified: ^11.0.5
    unist-util-visit: ^5.0.0

  prod:
    '@paralleldrive/cuid2': ^2.2.2
    dayjs: ^1.11.13
    superjson: ^2.2.2
    zod: ^3.25.61

  # 类型定义 (Type definitions)
  types:
    '@types/canvas-confetti': ^1.9.0
    '@types/hast': ^3.0.4
    '@types/mdast': ^4.0.4
    '@types/node': ^24.0.0
    '@types/pg': ^8.15.4
    '@types/react': 19.0.2
    '@types/react-dom': 19.0.3
    '@types/rss': ^0.0.32
    '@types/tinycolor2': ^1.4.6
    schema-dts: ^1.1.5

  script:
    cross-env: ^7.0.3
    dotenv-cli: ^8.0.0
    drizzle-kit: ^0.31.1
    fast-xml-parser: ^5.2.5
    plop: ^4.0.1
    taze: ^19.1.0
    tsx: ^4.20.1
    picocolors: ^1.1.1

  lint:
    '@eonova/eslint-config': ^0.3.1
    '@eslint-react/eslint-plugin': ^1.52.1
    eslint: ^9.28.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    knip: ^5.60.2
    cspell: ^9.0.2
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0

  ui:
    '@ark-ui/react': ^5.14.0
    '@tanstack/react-table': ^8.21.3
    '@icons-pack/react-simple-icons': 10.2.0
    '@number-flow/react': ^0.5.10
    '@radix-ui/react-alert-dialog': ^1.1.14
    '@radix-ui/react-aspect-ratio': ^1.1.7
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-dialog': ^1.1.14
    '@radix-ui/react-dropdown-menu': ^2.1.15
    '@radix-ui/react-label': ^2.1.7
    '@radix-ui/react-popover': ^1.1.14
    '@radix-ui/react-scroll-area': ^1.2.9
    '@radix-ui/react-select': ^2.2.5
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slot': ^1.2.3
    '@radix-ui/react-tooltip': ^1.2.7
    '@radix-ui/react-visually-hidden': ^1.2.3
    '@react-email/components': 0.0.35
    '@tailwindcss/postcss': ^4.1.8
    '@tailwindcss/typography': ^0.5.16
    canvas-confetti: ^1.9.3
    gsap: ^3.13.0
    lenis: ^1.3.4
    lucide-react: ^0.514.0
    postcss: ^8.5.4
    postcss-load-config: ^6.0.1
    sonner: ^2.0.5
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.8
    yet-another-react-lightbox: ^3.23.2

  test:
    '@axe-core/playwright': ^4.10.2
    '@playwright/test': ^1.53.0
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/react': ^16.3.0
    '@vitest/coverage-v8': 3.2.1
    '@vitest/ui': ^3.2.3
    vitest: ^3.2.3
