packages:
  - ./*

catalogs:
  analysis:
    '@next/bundle-analyzer': ^16.0.5
    '@vercel/speed-insights': ^1.2.0
  backend:
    '@ai-sdk/deepseek': ^1.0.31
    '@aws-sdk/client-s3': 3.919.0
    '@aws-sdk/s3-request-presigner': 3.919.0
    '@fastify/deepmerge': 3.1.0
    '@octokit/rest': ^22.0.1
    '@orpc/client': ^1.12.0
    '@orpc/server': ^1.12.0
    '@orpc/tanstack-query': ^1.12.0
    '@tanstack/react-query': ^5.90.11
    '@tanstack/react-query-devtools': ^5.91.1
    '@upstash/ratelimit': ^2.0.7
    '@upstash/redis': ^1.35.7
    ai: ^5.0.108
    better-auth: ^1.4.3
    better-call: ^1.1.3
    consola: ^3.4.2
    drizzle-orm: ^0.44.7
    drizzle-zod: ^0.8.3
    jose: ^6.1.2
    postgres: 3.4.7
    resend: ^6.5.2
    server-only: ^0.0.1
  build:
    '@vitejs/plugin-react': ^5.1.1
    babel-plugin-react-compiler: 19.0.0-beta-714736e-20250131
    sharp: ^0.34.5
    typescript: 5.7.3
  frontend:
    '@ducanh2912/next-pwa': ^10.2.9
    '@hookform/resolvers': ^5.2.2
    '@radix-ui/react-visually-hidden': ^1.2.4
    '@t3-oss/env-nextjs': ^0.13.8
    '@tanstack/react-form': ^1.26.0
    bowser: ^2.13.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    cn-fontsource-ding-talk-jin-bu-ti-regular: ^1.0.3
    cn-fontsource-yozai-medium: ^1.0.6
    cobe: ^0.6.5
    cva: 1.0.0-beta.3
    embla-carousel-react: ^8.6.0
    geist: ^1.5.1
    input-otp: ^1.4.2
    merge-refs: ^2.0.0
    motion: ^12.23.24
    next: 16.0.7
    next-themes: ^0.4.6
    nuqs: ^2.8.1
    posthog-js: ^1.298.1
    react: 19.2.1
    react-day-picker: ^9.11.3
    react-dom: 19.2.1
    react-email: 4.3.2
    react-hook-form: ^7.67.0
    react-intersection-observer: ^10.0.0
    react-medium-image-zoom: ^5.4.0
    react-resizable-panels: ^3.0.6
    react-spring: ^10.0.3
    rss: ^1.2.2
    tinycolor2: ^1.6.0
    tw-animate-css: ^1.4.0
    vaul: ^1.1.2
    zustand: ^5.0.9
  lint:
    '@antfu/eslint-config': ^6.2.0
    '@eslint-react/eslint-plugin': ^2.3.9
    cspell: ^9.3.2
    eslint: ^9.39.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    knip: ^5.70.2
    lint-staged: ^16.2.7
    prettier: ^3.7.3
    prettier-plugin-organize-imports: ^4.3.0
    prettier-plugin-tailwindcss: ^0.7.1
    simple-git-hooks: ^2.13.1
  mdx:
    '@content-collections/cli': ^0.1.7
    '@content-collections/core': ^0.12.0
    '@content-collections/mdx': ^0.2.2
    '@content-collections/next': ^0.2.9
    '@shikijs/rehype': ^3.17.0
    '@shikijs/transformers': ^3.17.0
    github-slugger: ^2.0.0
    markdown-to-jsx: 9.2.0
    remark: ^15.0.1
    remark-gfm: ^4.0.1
    shiki: ^3.17.0
    unified: ^11.0.5
    unist-util-visit: ^5.0.0
  prod:
    '@paralleldrive/cuid2': ^3.1.0
    dayjs: ^1.11.19
    zod: ^4.1.13
  script:
    cross-env: ^10.1.0
    dotenv-cli: ^11.0.0
    drizzle-kit: ^0.31.7
    execa: ^9.6.1
    picocolors: ^1.1.1
    plop: ^4.0.4
    taze: ^19.9.2
    tsx: ^4.20.6
  test:
    '@axe-core/playwright': ^4.11.0
    '@playwright/test': ^1.57.0
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.0
    '@vitest/coverage-v8': 3.2.1
    '@vitest/ui': ^4.0.14
    jsdom: ^27.2.0
    vitest: ^4.0.14
  types:
    '@types/canvas-confetti': ^1.9.0
    '@types/hast': ^3.0.4
    '@types/mdast': ^4.0.4
    '@types/node': ^24.10.1
    '@types/react': 19.2.2
    '@types/react-dom': 19.2.2
    '@types/rss': ^0.0.32
    '@types/spotify-api': ^0.0.25
    '@types/tinycolor2': ^1.4.6
    discord-api-types: ^0.38.35
    schema-dts: ^1.1.5
  ui:
    '@ark-ui/react': ^5.29.1
    '@icons-pack/react-simple-icons': 10.2.0
    '@number-flow/react': ^0.5.10
    '@react-email/components': 0.5.7
    '@react-email/preview-server': 4.3.2
    '@tailwindcss/postcss': ^4.1.17
    '@tailwindcss/typography': ^0.5.19
    '@tanstack/react-table': ^8.21.3
    canvas-confetti: ^1.9.4
    gsap: ^3.13.0
    lenis: ^1.3.15
    lucide-react: ^0.555.0
    postcss: ^8.5.6
    postcss-load-config: ^6.0.1
    radix-ui: ^1.4.3
    sonner: ^2.0.7
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.17
    yet-another-react-lightbox: ^3.25.0
