packages:
  - './*'

catalogs:
  analysis:
    '@next/bundle-analyzer': ^16.0.0
    '@vercel/speed-insights': ^1.2.0
    react-scan: ^0.4.3

  # 前端依赖 (Frontend development)
  frontend:
    '@ducanh2912/next-pwa': ^10.2.9
    '@hookform/resolvers': ^5.2.2
    '@next/bundle-analyzer': ^16.0.0
    '@t3-oss/env-nextjs': ^0.13.8
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    cobe: ^0.6.5
    cva: 1.0.0-beta.3
    geist: ^1.5.1
    merge-refs: ^2.0.0
    motion: ^12.23.24
    next: ^15.2.4
    next-themes: ^0.4.6
    nuqs: ^2.7.2
    react: 19.0.0
    react-day-picker: ^9.11.1
    react-dom: 19.0.0
    react-email: 4.0.3
    react-hook-form: ^7.65.0
    react-intersection-observer: ^9.16.0
    react-medium-image-zoom: ^5.4.0
    react-spring: ^10.0.3
    react-textarea-autosize: ^8.5.9
    rss: ^1.2.2
    tinycolor2: ^1.6.0
    zustand: ^5.0.8

  backend:
    '@octokit/rest': ^22.0.0
    '@tanstack/react-query': ^5.90.5
    '@tanstack/react-query-devtools': ^5.90.2
    '@trpc/client': ^11.6.0
    '@trpc/server': ^11.6.0
    '@trpc/tanstack-react-query': ^11.6.0
    '@upstash/ratelimit': ^2.0.6
    '@upstash/redis': ^1.35.6
    better-auth: ^1.3.29
    better-call: ^1.0.24
    drizzle-orm: ^0.44.7
    js-sha512: ^0.9.0
    openai: ^6.6.0
    pg: ^8.16.3
    resend: ^6.2.2

  build:
    '@vitejs/plugin-react': ^5.1.0
    babel-plugin-react-compiler: 19.0.0-beta-714736e-20250131
    critters: ^0.0.25
    next: 15.4.7
    sharp: ^0.34.2
    typescript: 5.7.3

  mdx:
    '@content-collections/cli': ^0.1.7
    '@content-collections/core': ^0.11.1
    '@content-collections/mdx': ^0.2.2
    '@content-collections/next': ^0.2.8
    '@shikijs/rehype': ^3.13.0
    '@shikijs/transformers': ^3.13.0
    markdown-to-jsx: ^7.7.17
    github-slugger: ^2.0.0
    remark: ^15.0.1
    remark-gfm: ^4.0.1
    shiki: ^3.13.0
    unified: ^11.0.5
    unist-util-visit: ^5.0.0

  prod:
    '@paralleldrive/cuid2': ^3.1.0
    dayjs: ^1.11.18
    superjson: ^2.2.3
    zod: ^4.1.12

  # 类型定义 (Type definitions)
  types:
    '@types/canvas-confetti': ^1.9.0
    '@types/hast': ^3.0.4
    '@types/mdast': ^4.0.4
    '@types/node': ^24.9.1
    '@types/pg': ^8.15.5
    '@types/react': 19.0.2
    '@types/react-dom': 19.0.3
    '@types/rss': ^0.0.32
    '@types/tinycolor2': ^1.4.6
    schema-dts: ^1.1.5

  script:
    cross-env: ^10.1.0
    dotenv-cli: ^10.0.0
    drizzle-kit: ^0.31.5
    fast-xml-parser: ^5.3.0
    plop: ^4.0.4
    taze: ^19.8.1
    tsx: ^4.20.6
    picocolors: ^1.1.1

  lint:
    '@eonova/eslint-config': ^0.3.1
    '@eslint-react/eslint-plugin': ^1.52.2
    eslint: ^9.29.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    knip: ^5.66.2
    cspell: ^9.2.2
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    prettier: ^3.6.2
    prettier-plugin-organize-imports: ^4.3.0
    prettier-plugin-tailwindcss: ^0.7.1

  ui:
    '@ark-ui/react': ^5.26.2
    '@dnd-kit/core': ^6.3.1
    '@dnd-kit/modifiers': ^9.0.0
    '@dnd-kit/sortable': ^10.0.0
    '@dnd-kit/utilities': ^3.2.2
    '@tanstack/react-table': ^8.21.3
    '@icons-pack/react-simple-icons': 10.2.0
    '@number-flow/react': ^0.5.10
    '@radix-ui/react-alert-dialog': ^1.1.15
    '@radix-ui/react-aspect-ratio': ^1.1.7
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-checkbox': ^1.3.3
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-label': ^2.1.7
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-scroll-area': ^1.2.10
    '@radix-ui/react-select': ^2.2.6
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slider': ^1.3.6
    '@radix-ui/react-slot': ^1.2.3
    '@radix-ui/react-tooltip': ^1.2.8
    '@radix-ui/react-visually-hidden': ^1.2.3
    '@react-email/components': 0.0.35
    '@tailwindcss/postcss': ^4.1.16
    '@tailwindcss/typography': ^0.5.19
    canvas-confetti: ^1.9.3
    gsap: ^3.13.0
    lenis: ^1.3.11
    lucide-react: ^0.547.0
    postcss: ^8.5.6
    postcss-load-config: ^6.0.1
    sonner: ^2.0.7
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.16
    yet-another-react-lightbox: ^3.25.0

  test:
    '@axe-core/playwright': ^4.11.0
    '@playwright/test': ^1.56.1
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.0
    '@vitest/coverage-v8': 3.2.1
    '@vitest/ui': ^4.0.2
    jsdom: ^27.0.1
    vitest: ^4.0.2
